#cloud-config
package_upgrade: true
packages:
  - nginx
  - certbot
  - python3
  - python3-certbot-nginx
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80 default_server;
        server_name _;
        root /var/www/html;
        index index.php index.html index.htm;
 
        location / {
            try_files $uri $uri/ =404;
        }
 
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        }
        }
  - owner: master:master
    path: /var/www/html/index.php
    content: |
      <?php echo "HTTP Host : ",$_SERVER['HTTP_HOST'],"<br>"; ?>
      <?php echo "HTTP Redirect : ",$_SERVER['REDIRECT_STATUS'],"<br>"; ?>
      <?php echo "Server Name : ",$_SERVER['SERVER_NAME'],"<br>"; ?>
      <?php echo "Server Port : ",$_SERVER['SERVER_PORT'],"<br>"; ?>
      <?php echo "Server Addr : ",$_SERVER['SERVER_ADDR'],"<br>"; ?>
      <?php echo "Caller IP : ",$_SERVER['REMOTE_ADDR'],"<br>"; ?>
      <?php echo "Document Root : ",$_SERVER['DOCUMENT_ROOT'],"<br>"; ?>
      <?php echo "User Agent : ",$_SERVER['HTTP_USER_AGENT'],"<br>"; ?>
      <?php echo "X-Forwarded-Host : ",$_SERVER['HTTP_X_FORWARDED_HOST'],"<br>"; ?>
      <?php echo "X-Forwarded-Proto : ",$_SERVER['HTTP_X_FORWARDED_PROTO'],"<br>"; ?>
      <?php echo "Document : ",$_SERVER['PHP_SELF'],"<br>"; ?>
runcmd:
  - sed /server_names_hash_bucket_size/s/64/128/g /etc/nginx/nginx.conf -i
  - sed /server_names_hash_bucket_size/s/\#//g /etc/nginx/nginx.conf -i
  - sudo apt install software-properties-common -y
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt update -y
  - sudo apt install php7.4 php7.4-fpm -y
  - nginx -s reload
  - certbot --nginx -d $(curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/userData?api-version=2021-02-01&format=text" | base64 -d) --register-unsafely-without-email --agree-tos --no-redirect